spring.application.name=tour-management-api

# Upload media location
media.location=/Users/nunea/Desktop/tour-management-system/media-upload/

# Custom file size
# Default 1MB

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
media.client-path = /media
#media.base-uri=http://localhost:1403
media.base-uri=http://10.0.2.2:1403

# Keycloak configuration
keycloak.auth-server-url=http://localhost:1401
keycloak.client-id=postman-app
keycloak.realm=tour-system
keycloak.client-secret=LFcXkw7QFVdt5C22dM1adPKA43d6rsdl


# Security configuration
spring.security.user.name=admin
spring.security.user.password=123456
spring.security.user.roles=CUSTOMER


#==========  Configure oauth2 resource server for postman =======
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:1401/realms/tour-system
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:1401/realms/tour-system/protocol/openid-connect/certs



# ===========  Configure oauth2 resource server for mobile app =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://10.0.2.2:1401/realms/tour-system
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:1401/realms/tour-system/protocol/openid-connect/certs

# Server Configuration
server.port=1403
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:1400/tour_system_db
spring.datasource.username=admin
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
